# OpsPilot AI — developer shortcuts.
# Requires: docker, uv. Run from the repo root.

BACKEND := backend

.PHONY: help
help:
	@echo "db-up        start PostgreSQL + pgvector"
	@echo "db-down      stop the database"
	@echo "sync         install backend deps (dev group)"
	@echo "sync-ml      install backend deps incl. the local embedding model"
	@echo "migrate      alembic upgrade head"
	@echo "migration m='msg'   create a new autogenerated migration"
	@echo "api          run the API with reload"
	@echo "test         fast tests (no infra)"
	@echo "test-all     full tests (needs db-up)"
	@echo "lint         ruff check + format check + mypy"
	@echo "fmt          ruff format"
	@echo "up / down    full docker-compose stack"
	@echo "gen          (re)build the synthetic knowledge base -> data/generated"
	@echo "gen-check    fail if data/generated is stale for the default seed"
	@echo "gen-test / gen-lint   test / lint the generator"
	@echo "ingest       ingest data/generated -> the configured Postgres (idempotent)"
	@echo "ingest-dry-run   load + chunk data/generated without touching the DB"
	@echo "eval-load    load data/generated/ground_truth.json -> evaluation_cases"
	@echo "eval-run     run the pipeline over the dev split (OPSPILOT_RETRIEVAL_STRATEGY)"
	@echo "eval-experiment   run vector + lexical + hybrid back to back, then report"
	@echo "eval-experiment-rerank   hybrid with vs without the cross-encoder, then report"
	@echo "eval-experiment-agent    one-shot vs deterministic vs agent on hard incidents (needs a real LLM key)"
	@echo "eval-report  print the cross-run comparison table"
	@echo "ml-dataset   build the labeled reranker fine-tuning dataset -> ml/datasets"
	@echo "ml-train     fine-tune the cross-encoder reranker -> ml/checkpoints"
	@echo "ml-experiment3   A/B/C reranker comparison on the held-out test chains (needs db-up + ingest)"
	@echo "ml-test / ml-lint   test / lint the ml/ reranker training pipeline"

.PHONY: db-up db-down up down
db-up:      ; docker compose up -d db
db-down:    ; docker compose stop db
up:         ; docker compose up
down:       ; docker compose down

.PHONY: sync sync-ml
sync:       ; cd $(BACKEND) && uv sync --group dev
sync-ml:    ; cd $(BACKEND) && uv sync --group dev --extra ml

.PHONY: migrate migration api
migrate:    ; cd $(BACKEND) && uv run alembic upgrade head
migration:  ; cd $(BACKEND) && uv run alembic revision --autogenerate -m "$(m)"
api:        ; cd $(BACKEND) && uv run uvicorn opspilot.main:app --reload

.PHONY: test test-all lint fmt
test:       ; cd $(BACKEND) && uv run pytest -m "not integration"
test-all:   ; cd $(BACKEND) && uv run pytest
lint:       ; cd $(BACKEND) && uv run ruff check . && uv run ruff format --check . && uv run mypy src
fmt:        ; cd $(BACKEND) && uv run ruff format .

# --- Phase 2: synthetic knowledge-base generator (stdlib only) -------------
GEN := uv run --project $(BACKEND) python
.PHONY: gen gen-check gen-test gen-lint
gen:        ; $(GEN) -m data.generator
gen-check:  ; $(GEN) -m data.generator --check
gen-test:   ; cd $(BACKEND) && uv run pytest ../data/generator/tests -q
gen-lint:   ; cd $(BACKEND) && uv run ruff check ../data && uv run ruff format --check ../data && uv run mypy --config-file ../pyproject.toml ../data

# --- Phase 3: ingest the synthetic corpus into Postgres --------------------
.PHONY: ingest ingest-dry-run
ingest:          ; cd $(BACKEND) && uv run python -m opspilot.ingestion
ingest-dry-run:  ; cd $(BACKEND) && uv run python -m opspilot.ingestion --dry-run

# --- Phase 4: evaluation harness --------------------------------------------
.PHONY: eval-load eval-run eval-experiment eval-experiment-rerank eval-report
eval-load:   ; cd $(BACKEND) && uv run python -m opspilot.evaluation load-cases
eval-run:    ; cd $(BACKEND) && uv run python -m opspilot.evaluation run
eval-report: ; cd $(BACKEND) && uv run python -m opspilot.evaluation report

# Phase 5: the vector-vs-lexical-vs-hybrid retrieval experiment (one run each).
eval-experiment:
	cd $(BACKEND) && uv run python -m opspilot.evaluation run --strategy vector  --notes "exp1 vector" \
	 && uv run python -m opspilot.evaluation run --strategy lexical --notes "exp1 lexical" \
	 && uv run python -m opspilot.evaluation run --strategy hybrid  --notes "exp1 hybrid" \
	 && uv run python -m opspilot.evaluation report

# Phase 6: hybrid with vs without the cross-encoder reranker.
eval-experiment-rerank:
	cd $(BACKEND) && uv run python -m opspilot.evaluation run --strategy hybrid --reranker none          --notes "exp2 hybrid" \
	 && uv run python -m opspilot.evaluation run --strategy hybrid --reranker cross_encoder --notes "exp2 hybrid+rerank" \
	 && uv run python -m opspilot.evaluation report

# Phase 9: one-shot RAG vs deterministic hybrid vs the LangGraph agent, on the
# hard (multi_hop/adversarial) incidents. NEEDS OPSPILOT_LLM_PROVIDER=anthropic
# + OPSPILOT_ANTHROPIC_API_KEY — under the default fake provider every case
# abstains for all three, which is a real (if useless) result, not an error.
.PHONY: eval-experiment-agent
eval-experiment-agent:
	cd $(BACKEND) && uv run python -m opspilot.evaluation run --strategy vector --difficulty multi_hop,adversarial --notes "exp4 one-shot vector" \
	 && uv run python -m opspilot.evaluation run --strategy hybrid --reranker none --difficulty multi_hop,adversarial --notes "exp4 deterministic hybrid" \
	 && uv run python -m opspilot.evaluation run --strategy agent --difficulty multi_hop,adversarial --notes "exp4 agent" \
	 && uv run python -m opspilot.evaluation report

# --- Phase 7: fine-tuned PyTorch cross-encoder reranker -------------------
ML := uv run --project $(BACKEND) python
.PHONY: ml-dataset ml-train ml-experiment3 ml-lint ml-test
ml-dataset:     ; $(ML) ml/build_dataset.py
ml-train:       ; $(ML) ml/train_reranker.py
ml-experiment3: ; $(ML) ml/eval_experiment3.py
ml-test:        ; cd $(BACKEND) && uv run pytest ../ml/tests -q
ml-lint:
	cd $(BACKEND) && uv run ruff check ../ml && uv run ruff format --check ../ml \
	 && uv run mypy --config-file pyproject.toml ../ml
