# OpsPilot AI — developer shortcuts.
# Requires: docker, uv. Run from the repo root.

BACKEND := backend

.PHONY: help
help:
	@echo "db-up        start PostgreSQL + pgvector"
	@echo "db-down      stop the database"
	@echo "sync         install backend deps (dev group)"
	@echo "sync-ml      install backend deps incl. the local embedding model"
	@echo "migrate      alembic upgrade head"
	@echo "migration m='msg'   create a new autogenerated migration"
	@echo "api          run the API with reload"
	@echo "test         fast tests (no infra)"
	@echo "test-all     full tests (needs db-up)"
	@echo "lint         ruff check + format check + mypy"
	@echo "fmt          ruff format"
	@echo "up / down    full docker-compose stack"
	@echo "gen          (re)build the synthetic knowledge base -> data/generated"
	@echo "gen-check    fail if data/generated is stale for the default seed"
	@echo "gen-test / gen-lint   test / lint the generator"

.PHONY: db-up db-down up down
db-up:      ; docker compose up -d db
db-down:    ; docker compose stop db
up:         ; docker compose up
down:       ; docker compose down

.PHONY: sync sync-ml
sync:       ; cd $(BACKEND) && uv sync --group dev
sync-ml:    ; cd $(BACKEND) && uv sync --group dev --extra ml

.PHONY: migrate migration api
migrate:    ; cd $(BACKEND) && uv run alembic upgrade head
migration:  ; cd $(BACKEND) && uv run alembic revision --autogenerate -m "$(m)"
api:        ; cd $(BACKEND) && uv run uvicorn opspilot.main:app --reload

.PHONY: test test-all lint fmt
test:       ; cd $(BACKEND) && uv run pytest -m "not integration"
test-all:   ; cd $(BACKEND) && uv run pytest
lint:       ; cd $(BACKEND) && uv run ruff check . && uv run ruff format --check . && uv run mypy src
fmt:        ; cd $(BACKEND) && uv run ruff format .

# --- Phase 2: synthetic knowledge-base generator (stdlib only) -------------
GEN := uv run --project $(BACKEND) python
.PHONY: gen gen-check gen-test gen-lint
gen:        ; $(GEN) -m data.generator
gen-check:  ; $(GEN) -m data.generator --check
gen-test:   ; cd $(BACKEND) && uv run pytest ../data/generator/tests -q
gen-lint:   ; cd $(BACKEND) && uv run ruff check ../data && uv run ruff format --check ../data && uv run mypy --config-file ../pyproject.toml ../data
